apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: draftapp-dev
  generateName: hello-world-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: seq-generator-task
            template: seq-generator
            arguments:
              parameters:
                - name: end
                  value: 100
          - name: random-int-task
            template: gen-random-int
            dependencies: [seq-generator-task]
            withParam: "{{tasks.seq-generator-task.outputs.result}}"
          - name: print-task
            template: print-result
            dependencies: [random-int-task]
            arguments:
              parameters:
                - name: aggregate-results
                  value: "{{tasks.random-int-task.outputs.result}}"
          - name: sleep-task
            template: sleep
            dependencies: [print-task]

    - name: sleep
      suspend:
        duration: "10s"

    - name: seq-generator
      inputs:
        parameters:
          - name: end
      script:
        image: alpine:latest
        command: [sh]
        source: |
          # Assign the end parameter to a variable
          end={{inputs.parameters.end}}
          # Generate the JSON array
          json_array="["
          i=1
          while [ $i -le $end ]; do
            json_array="$json_array$i"
            if [ $i -lt $end ]; then
              json_array="$json_array, "
            fi
            i=$((i + 1))
          done
          json_array="$json_array]"

          # Print the JSON array
          echo $json_array

    - name: print-result
      inputs:
        parameters:
          - name: aggregate-results
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo results: "{{inputs.parameters.aggregate-results}}",

    - name: gen-random-int
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import random
          i = random.randint(1, 100)
          print(str(i))
