apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: draftapp-dev
  generateName: kaniko-docker-workflow-
spec:
  entrypoint: docker-commands
  volumeClaimTemplates: # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir # name of volume claim
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
  templates:
    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        command:
          - /kaniko/executor
        args:
          - --dockerfile=Dockerfile
          - --context=/workdir
          - --destination=registry-svc.registry:80/hello-world:latest
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: generate-context
      script:
        image: alpine:3.11
        command: [sh]
        source: |
          #!/bin/sh
          echo "FROM hello-world:latest" > /workdir/Dockerfile
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: docker-commands
      steps:
        - - name: generate-dockerfile
            template: generate-context
        - - name: build-and-push
            template: kaniko-build
