apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-dpl
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-app
  template:
    metadata:
      labels:
        app: registry-app
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/docker/registry
      volumes:
        - name: config-volume
          secret:
            secretName: registry-config-sec
---
apiVersion: v1
kind: Service
metadata:
  namespace: registry
  name: registry-svc
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http-port
  selector:
    app: registry-app
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-config-sec
  namespace: registry
spec:
  encryptedData:
    config.yml: AgAfScytK6bAAtvRE+8wMzMynbxcdPUaMxEMBdNVFA/MRUdRHmup+jexboBfxxDpdfnyE2XRXX9A4TGjgxVnlNVm9IJlIJ+wzOOpebm2L4pC7ucy8LmrvydPFiHMstdmD+KOvwO4cKwfdIBLvw1SEC+LPZ3H7Fke6v4DdebU/iMtmHJIlhSvsrW/PFXfKMDtuv+88q5fSoQfNXiaXQnQWmOp6GiAP9QYBO1Isv5nD+bRL91ByEF8po/JaHDbDPdFeLEtrWqi6T2+ODWrx+0DvW27tYj1Kk5VFgcCVZJU2osAT7YN1ANR1zucjFsZiff2DrObRIKCzE85AlvFnG6cPsBV3Yj2Xgd27WuLBiYwlJ191dfLjDk7P3ENXuU2o39NLWTuBl5e5xfE2zB7wJDYymk1ZDNK/dP0cU3OayeYo+NK7Ka5t+fRLxxn3UBFQe8fn6NalFFMLlU6gTFQ8eADIN/na1LQ8IC8ejovt5TfJqL/8QGUJPdmL5Vwh/qfXoT3QbYtk0PiRadk5ZC1lo5UtQVPWD0zDu0b7JsFd50q4ZouVWB2LaA0GrsxR/NPlNJJ+GbrJqccH9ShCkDMs2q5lg2TYA1uRbcMQ26IkVkT+HxPBThbE2Tre2sGc7XGllvzPlQbd1GChSIEQJezJqjudsWCh0mduDF93pxCeuHTaofI+OLSgo0ysB3FrEYcEzSafYbqiHMxI4n9gePzyOcsAjaTi9rgbicwSfKj3TM0kHar/I92H6o7DwHOSaDBdb077eefpSEZm6iSQN1CVSenMMbG+6vJX7zptkoFTYX+jfHN5JNr1uLi04R3mzxj7iQMEGZHZ+sm5euYSOY5a/lJW6b+WRUNsrVgzg1mO/Sk5k5j0LDRt5RqmiuVV8J+W+xk1hLZrbuS62lv5d/Y/jb8nGCX7n8z6/WwNhPSw+IPZCB7Ph2MOfinFHp7C5xgcKzMiyP+CWliPcGPzOxLjk1phNgaLvuyiSzGnEZjyXCuQWaNNiBcBYzwjuNPxfTV1DsFB6B7EM0FDwRwdyStFavy3CZemj09UChZoNjOFQ2m/4WYRik9+/jIWE9VS25+gKXsOmMKfVM+9Fv161G0x/TDbfKK6sWFhC5SWwHUvryZ3kqvHsgLJvpnZlzUCh7VQGYKKw5q4qsJKb3uWEEUhX1QkBdjjKiwwBV4IhJY8CbmijRooO3Hhud/+ocuX+qL1wDeyDGoAKESWglQCs2nU8eIpce7+3o9/34YlHeYZvFOd3ObxUtnRxIwCW3qD58GhL0Wsc3jAmxT4Aj4l1HI/dGZzODcGKMluluWegCATg==
  template:
    metadata:
      creationTimestamp: null
      name: registry-config-sec
      namespace: registry
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: registry
  name: registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  ingressClassName: nginx
  rules:
    - host: docker-registry.geekembly.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-svc
                port:
                  name: http-port
