apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-dpl
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-app
  template:
    metadata:
      labels:
        app: registry-app
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/docker/registry
      volumes:
        - name: config-volume
          secret:
            secretName: registry-config-sec
---
apiVersion: v1
kind: Service
metadata:
  namespace: registry
  name: registry-svc
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http-port
  selector:
    app: registry-app
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-config-sec
  namespace: registry
spec:
  encryptedData:
    config.yml: AgA2RM8DSfdCGFE0ua2KoR6UA5Eej6AUrTpyapBI/kcSjkaVAx+WQF/aOEIA7rXNoUqYJ27/RawmJjtef/9sgWcliQln8wbd4Azr3aX2O0F7K3H0RmIjdsA4gQD3/sAt80FNu+zX7IP0F8tRIZhAs8OAKEx0CfoIAVq/Xi37wNSqfabqMWVAaAEwzYP+TfJ7DONQz2JdlniA4cY3F8s6ixvwobzRPgEkpd9dQzQLjvx7u6TMseOxuhokcSG/Sf2dJrhhiyZ4oFsQjh8upBxc1SkPmHb5hNo36OAPozDrqHeqUsc3N9Qbmn4k/Z/BqKV9qwkm/+BC015O4IZYSc5coaNtXQqJjpO3GYbM07EUJ+LC9aIN1BDjHunYAEAti/LsLv8hX9X2vAbVPoWuN2Ybwz3TTo6UPoP/92MVWYUtYWTd1co5BlsxasJUMCGDaSPdiLYPlgXerSwv/971t2ND+f+PKDZwwUj34V4HRguFi3K+VZcznE288Yd1/W82RNeZwbYb3GMJX3w4q4fG24zPUpLQDKCAnknhDMAHCAkRL7IgdMd+fI7T8LxyPEHcCS3b1MrRIZNaL0jRDalwmWcUdxjk017miyJtXhOnWn5RIqFD8ioiQg1L9BO9ao0nqOcgkyktoTQEQOhMJ6OQL8Bp77e2mH5AfS7Z584dDeF1X3hhUcdwT4xRsTlHJaOmXgJiadLu1iM71su6x2XTMqztfbuAM/NdB8QGJFTWWeRfAAy21AQm7KDseR2SqvUEhGG4bSvth2sQQka+yovygPz6koZAYaUKT2Dw/9mgGa4IoCsyDhRmshrrxZNYi1x7sjVtk01+c0uIS0zq3kNP4tBYXs5lsjUU5pFmI4Tq8t1OtGu95OyrrHWP3ezRTkHg4lBV3wHXPNQdumUGInvX18fvEELcWxIMtcSompjRgSKCWXVtt5diICQNyxBx3PTblC/0lJ8iL577zBdIL6Ohw6OaKi/kv5muRCB9EohXPzi8FbvfAY+tZ6xWWOnJPmq9zkzdI02sNYnce8Yrdekykc+ueN0Wsxbzi4WX8ACBrWJAK3X7iZ1ke9BHOxHwJleaEKs=
  template:
    metadata:
      creationTimestamp: null
      name: registry-config-sec
      namespace: registry
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: registry
  name: registry
spec:
  ingressClassName: nginx
  rules:
    - host: docker-registry.geekembly.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-svc
                port:
                  name: http-port
