---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-config-sec
  namespace: registry
spec:
  encryptedData:
    config.yml: AgCHg0nK1p26aKWLFWQ9RxVLS8aBC3hWcsZbPMhTGMZEl2jErn/B7tW6KnJhiXtA76hVjfeUa4JxRC3GBu7vWOdjoqgTPZbdUxMy6D5UPsNqehPvTMcEKe8I2K9pLBZfyqPahYsp/daHipa/MmAzdavp9bx9SlQWsOvtv6VHgHCiOQex4/3Sk2PlT8m0QUdHPjwa64e7LgymY/I7IeJOKMqOB6o6iH2U2UH5yMQoq/PWn7Ug6E6U79i5IM7jUK8a6n+mx2vNYNYZjoCeaTlV4auVgtJHQmq9uXc1pbf1BraIgRrX5ZPniR6Zao2DO9Q64cLj7Xk5CQS3/A5QjNQUtXBWqcOjf0tFQnXibqw/QhMN+vebu1Xl1nPChK83XauYfFYKV4BGYSOoNh0ckF7GcbNGr6fo4U+4VMbid8H1SZxWmWvKQrOJEh+dUCZw/nQ3QEfFVXB2FlewwvMASOheQ1r6UnlPfdazpNR510Gh7sBaNxXTuD0QKxMS67NQJRd0QLkvGqmAftQL9+RI+1MhT2OuTzJ07aDUuPY3TEhkzs6gyGPSC0iklOe0aGHBcKWk7AcT7sRPEfAVpe0+vRm3PjaX6YViQlKJhyxq8EoD5ojANbUsNdYnnvEKsYCNtZFRvO9JKr9X2rpvBo67EuK+ip8Nh4oGOAJtuCfqLMI6s63WZ/AE1qrWbn+lGiZRZaaR/eBnIzGbIW8NQB7Q1UNBCJnszgkgNiv997yWxQ6cO1ezAPsTi4p+n8UCWYVDizdWo8LmgJCjAkJU+Y5hoYJqOy3SffBGDvLsOhVmW4sTIbATUq4JhFfZxj3KAaX5h+9e3DAPwp4IyLMxuH1uDxMTeQsViVazMY8oOknBX3fBqUZKLm5m61AbFYX8Nv+XknDAlaUv0uwJUhANmhUwEtOemXrN7ZaTHHLmKISGbB9IWd2UBw57p/s5iKfZFFk7LdEt45VTPMFJWwiRaEqHALzaoCnq4Wow+eAhrQNaU3tJdU5a+v+G7tegVijhoWlzQxFGISJr3QADGVAQJ0m75eVzDd5Sm9B39pY4pNU8XKIacRqAeB/TFkY53ybtnCGh3TE0U9ynAOLOYoB/R1fuMf5jGhDsp43srtx/hijXZJxMd8ip/YSvTt097/mMuVPRKEcBiXDYM31aQzpHy78WA7CR7XK8GwQlX8Lo9PDITfB05qoWSuflQKcesF2MrmEHCHOkmGxYv0i80knE6aeskBgfVSnaJqHTmb2a1NzoPQ577XYLsQuM4i6pyJx6mz2faSY4ClZVa0vxHvwcmEDgYokhwQu6Qno7SG1xOlxcgaioCBkyBjz/xr7dA+b/BXJ2svTZjhdMQI7s3+SNnlBUsfPiRaL84euHqxaCPmwuwgBs5MVqIQfMpFgKr4JKVcftqLwBiotTECvA9d23Di2amxgHv+p6Wg07QQGDbnSTk0sJQzJxho6ylBafNZwZ+NBTMl+GHs2XEQVEpnxB2Uc8nq7cXP0BzcfDiqPm9QmTPywoepD1Sx6rr8U3lYvhQtzItv2QApqfHfWarpAzrv0E4AchlCs/aJGjDdP25MCn
  template:
    metadata:
      creationTimestamp: null
      name: registry-config-sec
      namespace: registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-auth-secret
  namespace: registry
spec:
  encryptedData:
    .htpasswd: AgCJxdFShkGNNXYLEEJ5ozEyQD40zoogZAf7mFLef/eLrDfa6FxVRLA7w+Wt7YiX6xRnQDQoxHFv5ANxXVAnlpcjKG5GYRPWRO7aeF+LTIXATQ38JQgVU011/Vlp0XcGQmQpCcVq4AKjeUSxQAKdz3x5cGeTap1Q3DgVqveJDPicr6v2Zv37hYO/M2Ul12bNOoGBSoCLp5OBYMtwPh6sg38+Ozf15FZmcFQq8vMFwedm+cWuTdTjSY4WKsZPyQV3Szl3NFdwQsqPgLsfSbxgQmm3DlgJ1afkxCmM4bRGzDyG3xPBEdL0CW3HpEpDGCQPPV45Lm8VTbnpz7fTpAGZqrqEhRhEnnBAOXTJ2dM2jBqOcuh4fzs3SY2D9Yp1Bmb6xlRKTM/YsauishfwlJ7dWAd0NacLg/TjqqvkYU26sH09Zoh7kbcAi+/DTWuOF1KBeeDTafLbxmX34UJBynwbALdbrdv1QAjct6r3Ponyiz6k1k+hAVyYdnyRTUO8EtUReQrXVsVwq9CRTlYyFdwLUi2WX8UFpTS392Crb172UHl82Sn0fltQs8KA7GdC7u01z4CLN2X07TJXe44LsnPnwtaPHngKULHuI4wiUYe+w4JtYjeeFwoinPkWXosHM0eBf5tmYmpNTR6VhrrXPCqnBoH60F3KDJCEYCGw0jH5WP11+2s3xSZYXWQzUe3kTdR21mkNz0ohIa99K1ZeF/wOZ01fTtkm507RdzXCzWEFFBCDSJkXfLI2UEQUGn5lhT8SzlMDgmz1g6vADRyE2BX04phjEZF5WoQ=
  template:
    metadata:
      creationTimestamp: null
      name: registry-auth-secret
      namespace: registry
