apiVersion: v1
kind: Namespace
metadata:
  name: draft
spec:
status:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: draft
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  namespace: draft
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
