apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: draft
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/draft
    repoURL: https://github.com/Cih2001/homelab.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
