apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: draftapp-dev
      namespace: argocd
    spec:
      destination:
        namespace: draftapp-dev
        server: https://kubernetes.default.svc
      project: default
      source:
        path: draftapp/deployments/base
        repoURL: https://github.com/Cih2001/homelab.git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
