cluster_name: homelab-k8s

kube_proxy_mode: iptables

helm_enabled: true

metallb_enabled: true
metallb_speaker_enabled: "{{ metallb_enabled }}"
metallb_namespace: "metallb-system"
metallb_version: v0.13.9
metallb_protocol: "layer2"
metallb_port: "7472"
metallb_memberlist_port: "7946"
metallb_config:
  speaker:
    nodeselector:
      kubernetes.io/os: "linux"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
  controller:
    nodeselector:
      kubernetes.io/os: "linux"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
  address_pools:
    primary:
      ip_range:
        - 10.100.0.128/25
      auto_assign: true
  layer2:
    - primary

ingress_nginx_enabled: true
ingress_nginx_service_type: LoadBalancer
ingress_nginx_namespace: "ingress-nginx"
ingress_nginx_insecure_port: 80
ingress_nginx_secure_port: 443
ingress_nginx_default: true

cert_manager_enabled: true
cert_manager_namespace: "cert-manager"

argocd_enabled: true
argocd_version: v2.11.0
argocd_namespace: argocd
